### ISSUE TITLE
canonical-kubernetes - Adding worker get stuck

### ISSUE THREAD

**Issue by ssebbass** [charmed-kubernetes/bundle#565] opened 2018-04-27 19:02 UTC
Hi Guys,

Today I was able to correctly deploy a kubernetes-cluster, but somehow it seems that adding a worker fails, here you have an extract of the `juju debug-log`.

```
2018-04-27 15:30:23 INFO juju-log Reactive main running for hook update-status
2018-04-27 15:30:24 INFO juju-log Initializing Snap Layer
2018-04-27 15:30:24 DEBUG update-status none
2018-04-27 15:30:24 INFO juju-log Invoking reactive handler: reactive/kubernetes_worker.py:257:charm_status
2018-04-27 15:30:24 INFO juju-log Invoking reactive handler: reactive/docker.py:341:enable_grub_cgroups
2018-04-27 15:30:24 INFO juju-log Invoking reactive handler: reactive/kubernetes_worker.py:301:send_data
2018-04-27 15:30:25 INFO juju-log Invoking reactive handler: reactive/tls_client.py:60:store_client
2018-04-27 15:30:25 INFO juju-log Invoking reactive handler: reactive/kubernetes_worker.py:234:set_app_version
2018-04-27 15:30:25 INFO juju-log Invoking reactive handler: reactive/tls_client.py:15:store_ca
2018-04-27 15:30:25 INFO juju-log Invoking reactive handler: reactive/kubernetes_worker.py:977:catch_change_in_creds
2018-04-27 15:30:26 INFO juju-log Invoking reactive handler: reactive/kubernetes_worker.py:965:request_kubelet_and_proxy_credentials
2018-04-27 15:30:26 INFO juju-log Invoking reactive handler: reactive/kubernetes_worker.py:956:notify_master_gpu_not_enabled
2018-04-27 15:30:26 INFO juju-log Setting gpu=False on kube-control relation
2018-04-27 15:30:26 INFO juju-log Invoking reactive handler: reactive/tls_client.py:36:store_server
2018-04-27 15:30:26 INFO juju-log Invoking reactive handler: reactive/kubernetes_worker.py:1007:fix_iptables_for_docker_1_13
2018-04-27 15:30:26 INFO juju-log Invoking reactive handler: reactive/kubernetes_worker.py:424:apply_node_labels
2018-04-27 15:30:27 INFO juju-log Skipping malformed option: .
2018-04-27 15:30:27 DEBUG update-status Error from server (NotFound): nodes "ip-10-0-3-204.ec2.internal" not found
2018-04-27 15:30:27 INFO juju-log Failed to apply label juju-application=kubernetes-worker. Will retry.
2018-04-27 15:30:28 DEBUG update-status Error from server (NotFound): nodes "ip-10-0-3-204.ec2.internal" not found
2018-04-27 15:30:28 INFO juju-log Failed to apply label juju-application=kubernetes-worker. Will retry.
2018-04-27 15:30:29 DEBUG update-status Error from server (NotFound): nodes "ip-10-0-3-204.ec2.internal" not found
2018-04-27 15:30:29 INFO juju-log Failed to apply label juju-application=kubernetes-worker. Will retry.
2018-04-27 15:30:30 DEBUG update-status Error from server (NotFound): nodes "ip-10-0-3-204.ec2.internal" not found
2018-04-27 15:30:30 INFO juju-log Failed to apply label juju-application=kubernetes-worker. Will retry.
```

[results-2018-04-27-15-29-04.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1956311/results-2018-04-27-15-29-04.tar.gz)

Any thoughts?

**Comment by Cynerva** [comment] 2018-04-27 19:44
I'm pretty sure you're hitting this: https://github.com/conjure-up/spells/issues/102

When you deploy canonical-kubernetes via conjure-up on AWS, the spell enables cloud native integration by attaching IAM profiles to the instances, and configuring Kubernetes services with `cloud-provider=aws`. This allows some features of Kubernetes to work that otherwise wouldn't: LoadBalancer service type, EBS persistent volumes, maybe other features too.

The downside is, Juju isn't aware of the IAM profile, so when you `juju add-unit kubernetes-worker`, the new instance does not have the profile attached. Kubelet initially succeeds at registering as a node, but shortly after, kube-controller-manager deletes the node because it doesn't recognize instances without the profile. This results in the `nodes "ip-10-0-3-204.ec2.internal" not found` error that you're seeing from the debug log.

I can think of two potential workarounds, though I've tested neither so your mileage may vary.

---

Option 1: If you don't need the extra functionality, you can disable AWS cloud native integration by removing `cloud-provider=aws` from the service arguments:
```
juju config kubernetes-master api-extra-args="" controller-manager-extra-args=""
juju config kubernetes-worker kubelet-extra-args=""
```

---

Option 2: You can manually attach the IAM profile to the new instance (you can see how the spell does it, [here](https://github.com/conjure-up/spells/blob/250c06c01381e1235530fae13e08a56ace05439c/canonical-kubernetes/steps/04_enable-cni/ec2/enable-cni#L109-L127)), and then restart kubelet with
```
juju run --application kubernetes-worker -- service snap.kubelet.daemon restart
```

---

I believe @johnsca has work in progress that will fix this issue, though it's a fairly hefty change and I imagine it will take us some time (weeks or months, perhaps) to get it out to stable. @tvansteenburgh @johnsca feel free to correct me if I'm wrong on that.

**Comment by Cynerva** [comment] 2018-04-27 20:53
Good question, I've never tried so I'm not sure. You're right that you'll need to manually add the role for new masters too. I'm not aware of any reason you'd need to restart the master services, but if you need to, here's how you would:

```
juju run --application kubernetes-master -- service snap.kube-apiserver.daemon restart
juju run --application kubernetes-master -- service snap.kube-controller-manager.daemon restart
juju run --application kubernetes-master -- service snap.kube-scheduler.daemon restart
```

**Comment by marcoceppi** [comment] 2018-04-27 21:02
You should only need to restart the kube-apiserver, neither controller
manager nor scheduler use cloud integration flags.

**Comment by dardelean** [comment] 2019-10-03 10:28
I am hitting the same thing for CDK 1.15 on a localhost deployment, so no AWS.

`unit-kubernetes-worker-3: 10:27:13 DEBUG unit.kubernetes-worker/3.update-status Error from server (NotFound): nodes "juju-ce00c0-11" not found
unit-kubernetes-worker-3: 10:27:13 INFO unit.kubernetes-worker/3.juju-log Failed to apply label juju-application=kubernetes-worker. Will retry.
unit-kubernetes-worker-3: 10:27:14 DEBUG unit.kubernetes-worker/3.update-status Error from server (NotFound): nodes "juju-ce00c0-11" not found
unit-kubernetes-worker-3: 10:27:14 INFO unit.kubernetes-worker/3.juju-log Failed to apply label juju-application=kubernetes-worker. Will retry.
unit-kubernetes-worker-3: 10:27:15 DEBUG unit.kubernetes-worker/3.update-status Error from server (NotFound): nodes "juju-ce00c0-11" not found
unit-kubernetes-worker-3: 10:27:16 INFO unit.kubernetes-worker/3.juju-log Failed to apply label juju-application=kubernetes-worker. Will retry.
unit-kubernetes-worker-3: 10:27:17 DEBUG unit.kubernetes-worker/3.update-status Error from server (NotFound): nodes "juju-ce00c0-11" not found
unit-kubernetes-worker-3: 10:27:17 INFO unit.kubernetes-worker/3.juju-log Failed to apply label juju-application=kubernetes-worker. Will retry.`

Tried to restart the daemons but no luck.

**Comment by hyperbolic2346** [comment] 2019-10-04 15:40
> I am hitting the same thing for CDK 1.15 on a localhost deployment, so no AWS.
> 
> Tried to restart the daemons but no luck.

I would suggest a new bug on [launchpad](https://bugs.launchpad.net/charmed-kubernetes), which is where we handle issues now. Be sure to attach the output of `juju crash-dump`. The error you list is just an error saying that kubelet is unable to register with the api server, but the cause could be many things.

**Comment by tvansteenburgh** [comment] 2019-10-04 16:26
> I would suggest a new bug on [launchpad](https://bugs.launchpad.net/charmed-kubernetes)

https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1846479

I'm closing this bug since the original cause has been addressed by the integrator charms for each cloud. For more info refer to the Cloud Integration section of the docs: https://ubuntu.com/kubernetes/docs

**Closed by tvansteenburgh** 2019-10-04 16:26 UTC
